plugins {
    id 'java'
    id 'maven-publish'
}

group = 'de.winniepat'
version = '0.1.0'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    maven {url = "https://repo.papermc.io/repository/maven-public/" }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url = uri("https://maven.winniepat.de/repository/maven-releases/")

            credentials {
                username = project.property("publish.username")
                password = project.property("publish.password")
                // the credentials from before are not valid anymore (I am not that dumb)
            }
        }
    }
}